# Generated by Django 5.0.6 on 2024-07-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='img',
        ),
        migrations.AddField(
            model_name='galery',
            name='img',
            field=models.ManyToManyField(blank=True, to='main.imagefield'),
        ),
    ]
