# Generated by Django 5.0.6 on 2024-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_brand_alter_product_galery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('SD', 'Default'), ('SH', 'Highlight')], default='SD', max_length=2),
        ),
    ]
